services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    networks:
      - dmpopidor_network

networks:
  dmpopidor_network:
    driver: "bridge"