services:
  app:
    container_name: pdf_generator
    build:
      context: .
    ports:
      - 30028:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    networks:
      - dmpopidor_dmpopidor_network

networks:
  dmpopidor_dmpopidor_network:
    external: true
